#!/bin/sh

HOME_BIN=$(readlink -m ~/bin)
TOOLS_DIR=$(dirname $(readlink -m $0))/bin
RESTORE_DIR=$(pwd)

if [ ! -d "${HOME_BIN}" ]; then
    mkdir ${HOME_BIN}
fi

if [ ! -w "${HOME_BIN}" ]; then
    echo "You have no write permission to ${HOME_BIN}" >&2
    exit 1
fi

cd "${TOOLS_DIR}"
chmod +x $(find . -type f | grep -v '.sh')

for FILE in $(ls -1); do

    FULL_PATH="${TOOLS_DIR}/${FILE}"

    if [ -d "${FULL_PATH}" ]; then
        if ! cp -Rf "${FULL_PATH}" "${HOME_BIN}"; then
            echo "There were errors copying files ${FULL_PATH} to ${HOME_BIN}" >&2
            exit 2
        fi
    elif [ -f "${FULL_PATH}" ]; then
        if ! cp "${FULL_PATH}" "${HOME_BIN}"; then
            echo "There were errors copying files ${FULL_PATH} to ${HOME_BIN}" >&2
            exit 2
        fi
    fi

done

cd "${HOME_BIN}"

chmod +x $(find . -type f | grep -v '.sh')

cd "${RESTORE_DIR}"
exit 0
